theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端工程师

# 对你自己的简洁描述
description: 正在努力中的小菜鸟

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: zzzz

# 你的联系方式
phone: 15388953445

# 你的邮箱
email: 3522829964@qq.com

# 你目前的住址
address: 湖南

# 你毕业院校
school: 湖南开放大学

# 你的专业
profession: 软件技术

# 你的学位
degree: 在读

# 你获得过的证书或奖励
credential:计算机二级
