＃你的求职方向，某些前端开发工程师等
职称：首席工程师

＃对你自己的简洁描述
简介：正在努力中的小菜鸟

＃你的美照地址
徽标：/assets/images/me.jpg

＃你的名字
名称：zzzz

＃你的联系方式
电话：15388953445

＃你的邮箱
电子邮件：3522829964@qq.com

＃你目前的住址
地址：湖南

＃你毕业学院
学校：湖南开放大学

＃你的专业
专业：软件技术

＃你的学位
程度：在读

＃你获得过的证书或奖励
凭证：计算机二级
